# coding: utf-8

"""
    Vouch Bridge

    C2PA image signing, QR badge overlay, and audio watermarking service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from setuptools import setup, find_packages  # noqa: H301

# To install the library, run the following
#
# python setup.py install
#
# prerequisite: setuptools
# http://pypi.python.org/pypi/setuptools
NAME = "vouch-api-client"
VERSION = "0.1.0"
PYTHON_REQUIRES = ">=3.7"
REQUIRES = [
    "urllib3 >= 1.25.3, < 2.1.0",
    "python-dateutil",
    "pydantic >= 2",
    "typing-extensions >= 4.7.1",
]

setup(
    name=NAME,
    version=VERSION,
    description="Typed HTTP client for the Vouch Protocol Bridge API (sign, verify, audio), generated from its OpenAPI spec.",
    author="Ramprasad Anandam Gaddam",
    author_email="hello@vouch-protocol.com",
    url="https://github.com/vouch-protocol/vouch",
    project_urls={"Homepage": "https://vouch-protocol.com"},
    license="Apache-2.0",
    keywords=["vouch", "verifiable-credentials", "api-client", "openapi"],
    install_requires=REQUIRES,
    packages=find_packages(exclude=["test", "tests"]),
    include_package_data=True,
    long_description_content_type='text/markdown',
    long_description="""\
    Typed HTTP client for the Vouch Protocol Bridge API (sign, verify, audio).
    """,  # noqa: E501
    package_data={"vouch_api_client": ["py.typed"]},
)
