# coding: utf-8

"""
    Vouch Bridge

    C2PA image signing, QR badge overlay, and audio watermarking service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vouch_api_client.models.audio_embed_request import AudioEmbedRequest

class TestAudioEmbedRequest(unittest.TestCase):
    """AudioEmbedRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AudioEmbedRequest:
        """Test AudioEmbedRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AudioEmbedRequest`
        """
        model = AudioEmbedRequest()
        if include_optional:
            return AudioEmbedRequest(
                audio_base64 = '',
                did = '',
                display_name = '',
                covenant = { }
            )
        else:
            return AudioEmbedRequest(
                audio_base64 = '',
                did = '',
        )
        """

    def testAudioEmbedRequest(self):
        """Test AudioEmbedRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
