# coding: utf-8

"""
    Vouch Bridge

    C2PA image signing, QR badge overlay, and audio watermarking service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vouch_api_client.models.sign_request import SignRequest

class TestSignRequest(unittest.TestCase):
    """SignRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> SignRequest:
        """Test SignRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `SignRequest`
        """
        model = SignRequest()
        if include_optional:
            return SignRequest(
                image_base64 = '',
                did = '',
                display_name = '',
                email = '',
                credential_type = 'FREE',
                title = '',
                badge_position = '',
                shortlink_domain = ''
            )
        else:
            return SignRequest(
                image_base64 = '',
                did = '',
                display_name = '',
        )
        """

    def testSignRequest(self):
        """Test SignRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
