# coding: utf-8

"""
    Vouch Bridge

    C2PA image signing, QR badge overlay, and audio watermarking service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vouch_api_client.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_health_health_get(self) -> None:
        """Test case for health_health_get

        Health
        """
        pass

    def test_sign_image_sign_post(self) -> None:
        """Test case for sign_image_sign_post

        Sign Image
        """
        pass

    def test_verify_image_verify_post(self) -> None:
        """Test case for verify_image_verify_post

        Verify Image
        """
        pass


if __name__ == '__main__':
    unittest.main()
