# coding: utf-8

"""
    Vouch Bridge

    C2PA image signing, QR badge overlay, and audio watermarking service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vouch_api_client.models.verify_request import VerifyRequest

class TestVerifyRequest(unittest.TestCase):
    """VerifyRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> VerifyRequest:
        """Test VerifyRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `VerifyRequest`
        """
        model = VerifyRequest()
        if include_optional:
            return VerifyRequest(
                image_base64 = ''
            )
        else:
            return VerifyRequest(
                image_base64 = '',
        )
        """

    def testVerifyRequest(self):
        """Test VerifyRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
