# coding: utf-8

"""
    Vouch Bridge

    C2PA image signing, QR badge overlay, and audio watermarking service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from vouch_api_client.api.audio_api import AudioApi


class TestAudioApi(unittest.TestCase):
    """AudioApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AudioApi()

    def tearDown(self) -> None:
        pass

    def test_audio_detect_audio_detect_post(self) -> None:
        """Test case for audio_detect_audio_detect_post

        Audio Detect
        """
        pass

    def test_audio_embed_audio_embed_post(self) -> None:
        """Test case for audio_embed_audio_embed_post

        Audio Embed
        """
        pass

    def test_audio_health_audio_health_get(self) -> None:
        """Test case for audio_health_audio_health_get

        Audio Health
        """
        pass

    def test_audio_sign_audio_sign_post(self) -> None:
        """Test case for audio_sign_audio_sign_post

        Audio Sign
        """
        pass


if __name__ == '__main__':
    unittest.main()
