//! Cross-language interop for the disconnected-edge (DTN) robotics primitives.
//!
//! Loads the shared vector generated by `test-vectors/robotics/dtn_generate.py`
//! (Python-signed credentials, PAD-106 to PAD-124) and proves the Rust core verifies
//! every one of them, and reproduces the sparse-Merkle revocation root byte-for-byte.
//! This is the parity proof: a disconnected-edge credential signed in Python verifies
//! in Rust (and therefore in every UniFFI/WASM wrapper over the core).

use base64::engine::general_purpose::URL_SAFE_NO_PAD;
use base64::Engine;
use serde_json::Value;
use std::fs;

use vouch_core::robotics_dtn as dtn;

fn vector() -> Value {
    let path = concat!(env!("CARGO_MANIFEST_DIR"), "/../../test-vectors/robotics/dtn_vector.json");
    serde_json::from_str(&fs::read_to_string(path).expect("read dtn_vector.json")).expect("parse")
}

fn vec3(v: &Value) -> [f64; 3] {
    let a = v.as_array().expect("array");
    [a[0].as_f64().unwrap(), a[1].as_f64().unwrap(), a[2].as_f64().unwrap()]
}

#[test]
fn python_signed_dtn_credentials_verify_in_rust() {
    let doc = vector();
    let pk = URL_SAFE_NO_PAD
        .decode(doc["issuerPublicKeyRawB64Url"].as_str().unwrap())
        .expect("decode pubkey");

    for entry in doc["credentials"].as_array().unwrap() {
        let name = entry["name"].as_str().unwrap();
        let cred = &entry["credential"];
        let v = &entry["verify"];
        let kind = v["kind"].as_str().unwrap();

        let ok = match kind {
            "freshness_token" => dtn::verify_freshness_token(
                cred, &pk, v["verifierEpoch"].as_i64().unwrap(), v["tier"].as_str().unwrap(),
                None, None, None,
            )
            .unwrap()
            .is_some(),
            "presence" => dtn::verify_presence_attestation(
                cred, &pk, vec3(&v["verifierPosition"]), v["expectedNonce"].as_str(),
            )
            .unwrap()
            .is_some(),
            "geoscope" => {
                let sub = dtn::verify_geoscoped_grant(cred, &pk, None).unwrap();
                sub.as_ref().map(|s| dtn::geoscope_permits(s, vec3(&v["position"]))).unwrap_or(false)
            }
            "conditional_revocation" => dtn::verify_conditional_revocation(cred, &pk).unwrap().is_some(),
            "range_observation" => dtn::verify_range_observation(cred, &pk).unwrap().is_some(),
            "beam_presence" => dtn::verify_beam_presence(
                cred, &pk, vec3(&v["peerDirection"]), v["expectedNonce"].as_str(),
            )
            .unwrap()
            .is_some(),
            "distress" => dtn::verify_distress_attestation(cred, &pk).unwrap().is_some(),
            "trust_state_update" => dtn::verify_trust_state_update(cred, &pk).unwrap().is_some(),
            "time_quality" => {
                let sub = dtn::verify_time_quality_attestation(cred, &pk).unwrap();
                sub.as_ref().map(|s| dtn::time_quality_permits(s, v["tier"].as_str().unwrap(), None)).unwrap_or(false)
            }
            "integrity_risk" => dtn::verify_integrity_risk_attestation(cred, &pk).unwrap().is_some(),
            "perception_claim" => dtn::verify_perception_claim(cred, &pk).unwrap().is_some(),
            "bundle" => dtn::verify_bundle_trust(cred, &pk, v["payloadHash"].as_str().unwrap()).unwrap().is_some(),
            other => panic!("unknown verify kind: {other}"),
        };
        assert!(ok, "Rust failed to verify Python-signed credential: {name}");
    }
}

#[test]
fn accumulator_root_and_proofs_match_python() {
    let doc = vector();
    let pk = URL_SAFE_NO_PAD
        .decode(doc["issuerPublicKeyRawB64Url"].as_str().unwrap())
        .unwrap();
    let acc = &doc["accumulator"];

    // Reproduce the sparse-Merkle root byte-for-byte from the same revoked set.
    let mut tree = dtn::SparseMerkleTree::new();
    for cid in acc["revokedIds"].as_array().unwrap() {
        tree.revoke(cid.as_str().unwrap());
    }
    assert_eq!(
        tree.root_multibase(),
        acc["rootMultibase"].as_str().unwrap(),
        "Rust sparse-Merkle root must byte-match the Python root"
    );

    // Verify the Python-signed accumulator root + the Python-produced proofs.
    let signed = &acc["signedRoot"];
    assert!(
        dtn::verify_non_revocation(
            acc["nonRevokedId"].as_str().unwrap(),
            &acc["nonRevokedProof"],
            signed,
            &pk,
        )
        .unwrap(),
        "a non-revoked credential's Python proof must verify in Rust"
    );
    assert!(
        !dtn::verify_non_revocation(
            acc["revokedId"].as_str().unwrap(),
            &acc["revokedProof"],
            signed,
            &pk,
        )
        .unwrap(),
        "a revoked credential's proof must NOT verify"
    );
}
