/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /audio/embed.
 * @export
 * @interface AudioEmbedRequest
 */
export interface AudioEmbedRequest {
    /**
     * Base64-encoded audio (WAV/MP3/FLAC/OGG/M4A/AAC/Opus/WebM)
     * @type {string}
     * @memberof AudioEmbedRequest
     */
    audioBase64: string;
    /**
     * DID of the signer
     * @type {string}
     * @memberof AudioEmbedRequest
     */
    did: string;
    /**
     * Human-readable signer name
     * @type {string}
     * @memberof AudioEmbedRequest
     */
    displayName?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AudioEmbedRequest
     */
    covenant?: { [key: string]: any; } | null;
}

/**
 * Check if a given object implements the AudioEmbedRequest interface.
 */
export function instanceOfAudioEmbedRequest(value: object): value is AudioEmbedRequest {
    if (!('audioBase64' in value) || value['audioBase64'] === undefined) return false;
    if (!('did' in value) || value['did'] === undefined) return false;
    return true;
}

export function AudioEmbedRequestFromJSON(json: any): AudioEmbedRequest {
    return AudioEmbedRequestFromJSONTyped(json, false);
}

export function AudioEmbedRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioEmbedRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'audioBase64': json['audio_base64'],
        'did': json['did'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'covenant': json['covenant'] == null ? undefined : json['covenant'],
    };
}

export function AudioEmbedRequestToJSON(value?: AudioEmbedRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'audio_base64': value['audioBase64'],
        'did': value['did'],
        'display_name': value['displayName'],
        'covenant': value['covenant'],
    };
}

