/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for GET /audio/health.
 * @export
 * @interface AudioHealthResponse
 */
export interface AudioHealthResponse {
    /**
     * 
     * @type {string}
     * @memberof AudioHealthResponse
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof AudioHealthResponse
     */
    version: string;
    /**
     * 
     * @type {boolean}
     * @memberof AudioHealthResponse
     */
    numpyAvailable: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AudioHealthResponse
     */
    c2paAvailable: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AudioHealthResponse
     */
    audiosealAvailable: boolean;
    /**
     * 
     * @type {string}
     * @memberof AudioHealthResponse
     */
    watermarker: string;
}

/**
 * Check if a given object implements the AudioHealthResponse interface.
 */
export function instanceOfAudioHealthResponse(value: object): value is AudioHealthResponse {
    if (!('status' in value) || value['status'] === undefined) return false;
    if (!('version' in value) || value['version'] === undefined) return false;
    if (!('numpyAvailable' in value) || value['numpyAvailable'] === undefined) return false;
    if (!('c2paAvailable' in value) || value['c2paAvailable'] === undefined) return false;
    if (!('audiosealAvailable' in value) || value['audiosealAvailable'] === undefined) return false;
    if (!('watermarker' in value) || value['watermarker'] === undefined) return false;
    return true;
}

export function AudioHealthResponseFromJSON(json: any): AudioHealthResponse {
    return AudioHealthResponseFromJSONTyped(json, false);
}

export function AudioHealthResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioHealthResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
        'version': json['version'],
        'numpyAvailable': json['numpy_available'],
        'c2paAvailable': json['c2pa_available'],
        'audiosealAvailable': json['audioseal_available'],
        'watermarker': json['watermarker'],
    };
}

export function AudioHealthResponseToJSON(value?: AudioHealthResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'status': value['status'],
        'version': value['version'],
        'numpy_available': value['numpyAvailable'],
        'c2pa_available': value['c2paAvailable'],
        'audioseal_available': value['audiosealAvailable'],
        'watermarker': value['watermarker'],
    };
}

