/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for POST /audio/sign.
 * @export
 * @interface AudioSignResponse
 */
export interface AudioSignResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AudioSignResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof AudioSignResponse
     */
    signedAudioBase64?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AudioSignResponse
     */
    manifestHash?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof AudioSignResponse
     */
    watermarkEmbedded?: boolean;
    /**
     * 
     * @type {string}
     * @memberof AudioSignResponse
     */
    timestamp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AudioSignResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the AudioSignResponse interface.
 */
export function instanceOfAudioSignResponse(value: object): value is AudioSignResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function AudioSignResponseFromJSON(json: any): AudioSignResponse {
    return AudioSignResponseFromJSONTyped(json, false);
}

export function AudioSignResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioSignResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'signedAudioBase64': json['signed_audio_base64'] == null ? undefined : json['signed_audio_base64'],
        'manifestHash': json['manifest_hash'] == null ? undefined : json['manifest_hash'],
        'watermarkEmbedded': json['watermark_embedded'] == null ? undefined : json['watermark_embedded'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AudioSignResponseToJSON(value?: AudioSignResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'signed_audio_base64': value['signedAudioBase64'],
        'manifest_hash': value['manifestHash'],
        'watermark_embedded': value['watermarkEmbedded'],
        'timestamp': value['timestamp'],
        'error': value['error'],
    };
}

