/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /audio/sign — full C2PA container signing.
 * @export
 * @interface AudioSignRequest
 */
export interface AudioSignRequest {
    /**
     * Base64-encoded audio file
     * @type {string}
     * @memberof AudioSignRequest
     */
    audioBase64: string;
    /**
     * DID of the signer
     * @type {string}
     * @memberof AudioSignRequest
     */
    did: string;
    /**
     * Human-readable signer name
     * @type {string}
     * @memberof AudioSignRequest
     */
    displayName?: string;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AudioSignRequest
     */
    covenant?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof AudioSignRequest
     */
    title?: string | null;
}

/**
 * Check if a given object implements the AudioSignRequest interface.
 */
export function instanceOfAudioSignRequest(value: object): value is AudioSignRequest {
    if (!('audioBase64' in value) || value['audioBase64'] === undefined) return false;
    if (!('did' in value) || value['did'] === undefined) return false;
    return true;
}

export function AudioSignRequestFromJSON(json: any): AudioSignRequest {
    return AudioSignRequestFromJSONTyped(json, false);
}

export function AudioSignRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioSignRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'audioBase64': json['audio_base64'],
        'did': json['did'],
        'displayName': json['display_name'] == null ? undefined : json['display_name'],
        'covenant': json['covenant'] == null ? undefined : json['covenant'],
        'title': json['title'] == null ? undefined : json['title'],
    };
}

export function AudioSignRequestToJSON(value?: AudioSignRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'audio_base64': value['audioBase64'],
        'did': value['did'],
        'display_name': value['displayName'],
        'covenant': value['covenant'],
        'title': value['title'],
    };
}

