/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for POST /audio/embed.
 * @export
 * @interface AudioEmbedResponse
 */
export interface AudioEmbedResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AudioEmbedResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof AudioEmbedResponse
     */
    audioBase64?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AudioEmbedResponse
     */
    watermarkId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AudioEmbedResponse
     */
    audioHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AudioEmbedResponse
     */
    payloadHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AudioEmbedResponse
     */
    timestamp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AudioEmbedResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the AudioEmbedResponse interface.
 */
export function instanceOfAudioEmbedResponse(value: object): value is AudioEmbedResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function AudioEmbedResponseFromJSON(json: any): AudioEmbedResponse {
    return AudioEmbedResponseFromJSONTyped(json, false);
}

export function AudioEmbedResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioEmbedResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'audioBase64': json['audio_base64'] == null ? undefined : json['audio_base64'],
        'watermarkId': json['watermark_id'] == null ? undefined : json['watermark_id'],
        'audioHash': json['audio_hash'] == null ? undefined : json['audio_hash'],
        'payloadHash': json['payload_hash'] == null ? undefined : json['payload_hash'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AudioEmbedResponseToJSON(value?: AudioEmbedResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'audio_base64': value['audioBase64'],
        'watermark_id': value['watermarkId'],
        'audio_hash': value['audioHash'],
        'payload_hash': value['payloadHash'],
        'timestamp': value['timestamp'],
        'error': value['error'],
    };
}

