/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /audio/detect.
 * @export
 * @interface AudioDetectRequest
 */
export interface AudioDetectRequest {
    /**
     * Base64-encoded audio to scan
     * @type {string}
     * @memberof AudioDetectRequest
     */
    audioBase64: string;
}

/**
 * Check if a given object implements the AudioDetectRequest interface.
 */
export function instanceOfAudioDetectRequest(value: object): value is AudioDetectRequest {
    if (!('audioBase64' in value) || value['audioBase64'] === undefined) return false;
    return true;
}

export function AudioDetectRequestFromJSON(json: any): AudioDetectRequest {
    return AudioDetectRequestFromJSONTyped(json, false);
}

export function AudioDetectRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioDetectRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'audioBase64': json['audio_base64'],
    };
}

export function AudioDetectRequestToJSON(value?: AudioDetectRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'audio_base64': value['audioBase64'],
    };
}

