/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for POST /audio/detect.
 * @export
 * @interface AudioDetectResponse
 */
export interface AudioDetectResponse {
    /**
     * 
     * @type {boolean}
     * @memberof AudioDetectResponse
     */
    success: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof AudioDetectResponse
     */
    detected?: boolean;
    /**
     * 
     * @type {number}
     * @memberof AudioDetectResponse
     */
    confidence?: number;
    /**
     * 
     * @type {string}
     * @memberof AudioDetectResponse
     */
    signerDid?: string | null;
    /**
     * 
     * @type {string}
     * @memberof AudioDetectResponse
     */
    payloadHash?: string | null;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof AudioDetectResponse
     */
    covenant?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof AudioDetectResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the AudioDetectResponse interface.
 */
export function instanceOfAudioDetectResponse(value: object): value is AudioDetectResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function AudioDetectResponseFromJSON(json: any): AudioDetectResponse {
    return AudioDetectResponseFromJSONTyped(json, false);
}

export function AudioDetectResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AudioDetectResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'detected': json['detected'] == null ? undefined : json['detected'],
        'confidence': json['confidence'] == null ? undefined : json['confidence'],
        'signerDid': json['signer_did'] == null ? undefined : json['signer_did'],
        'payloadHash': json['payload_hash'] == null ? undefined : json['payload_hash'],
        'covenant': json['covenant'] == null ? undefined : json['covenant'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function AudioDetectResponseToJSON(value?: AudioDetectResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'detected': value['detected'],
        'confidence': value['confidence'],
        'signer_did': value['signerDid'],
        'payload_hash': value['payloadHash'],
        'covenant': value['covenant'],
        'error': value['error'],
    };
}

