/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for POST /sign.
 * @export
 * @interface SignResponse
 */
export interface SignResponse {
    /**
     * 
     * @type {boolean}
     * @memberof SignResponse
     */
    success: boolean;
    /**
     * 
     * @type {string}
     * @memberof SignResponse
     */
    signedImageBase64?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignResponse
     */
    manifestHash?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignResponse
     */
    verifyUrl?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignResponse
     */
    timestamp?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the SignResponse interface.
 */
export function instanceOfSignResponse(value: object): value is SignResponse {
    if (!('success' in value) || value['success'] === undefined) return false;
    return true;
}

export function SignResponseFromJSON(json: any): SignResponse {
    return SignResponseFromJSONTyped(json, false);
}

export function SignResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'success': json['success'],
        'signedImageBase64': json['signed_image_base64'] == null ? undefined : json['signed_image_base64'],
        'manifestHash': json['manifest_hash'] == null ? undefined : json['manifest_hash'],
        'verifyUrl': json['verify_url'] == null ? undefined : json['verify_url'],
        'timestamp': json['timestamp'] == null ? undefined : json['timestamp'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function SignResponseToJSON(value?: SignResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'success': value['success'],
        'signed_image_base64': value['signedImageBase64'],
        'manifest_hash': value['manifestHash'],
        'verify_url': value['verifyUrl'],
        'timestamp': value['timestamp'],
        'error': value['error'],
    };
}

