/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /sign.
 * @export
 * @interface SignRequest
 */
export interface SignRequest {
    /**
     * Base64-encoded source image
     * @type {string}
     * @memberof SignRequest
     */
    imageBase64: string;
    /**
     * DID of the signer
     * @type {string}
     * @memberof SignRequest
     */
    did: string;
    /**
     * Human-readable signer name
     * @type {string}
     * @memberof SignRequest
     */
    displayName: string;
    /**
     * 
     * @type {string}
     * @memberof SignRequest
     */
    email?: string | null;
    /**
     * FREE or PRO
     * @type {string}
     * @memberof SignRequest
     */
    credentialType?: string;
    /**
     * 
     * @type {string}
     * @memberof SignRequest
     */
    title?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignRequest
     */
    badgePosition?: string | null;
    /**
     * 
     * @type {string}
     * @memberof SignRequest
     */
    shortlinkDomain?: string | null;
}

/**
 * Check if a given object implements the SignRequest interface.
 */
export function instanceOfSignRequest(value: object): value is SignRequest {
    if (!('imageBase64' in value) || value['imageBase64'] === undefined) return false;
    if (!('did' in value) || value['did'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    return true;
}

export function SignRequestFromJSON(json: any): SignRequest {
    return SignRequestFromJSONTyped(json, false);
}

export function SignRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SignRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'imageBase64': json['image_base64'],
        'did': json['did'],
        'displayName': json['display_name'],
        'email': json['email'] == null ? undefined : json['email'],
        'credentialType': json['credential_type'] == null ? undefined : json['credential_type'],
        'title': json['title'] == null ? undefined : json['title'],
        'badgePosition': json['badge_position'] == null ? undefined : json['badge_position'],
        'shortlinkDomain': json['shortlink_domain'] == null ? undefined : json['shortlink_domain'],
    };
}

export function SignRequestToJSON(value?: SignRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'image_base64': value['imageBase64'],
        'did': value['did'],
        'display_name': value['displayName'],
        'email': value['email'],
        'credential_type': value['credentialType'],
        'title': value['title'],
        'badge_position': value['badgePosition'],
        'shortlink_domain': value['shortlinkDomain'],
    };
}

