/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for POST /verify.
 * @export
 * @interface VerifyRequest
 */
export interface VerifyRequest {
    /**
     * Base64-encoded image to verify
     * @type {string}
     * @memberof VerifyRequest
     */
    imageBase64: string;
}

/**
 * Check if a given object implements the VerifyRequest interface.
 */
export function instanceOfVerifyRequest(value: object): value is VerifyRequest {
    if (!('imageBase64' in value) || value['imageBase64'] === undefined) return false;
    return true;
}

export function VerifyRequestFromJSON(json: any): VerifyRequest {
    return VerifyRequestFromJSONTyped(json, false);
}

export function VerifyRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'imageBase64': json['image_base64'],
    };
}

export function VerifyRequestToJSON(value?: VerifyRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'image_base64': value['imageBase64'],
    };
}

