/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Response body for POST /verify.
 * @export
 * @interface VerifyResponse
 */
export interface VerifyResponse {
    /**
     * 
     * @type {boolean}
     * @memberof VerifyResponse
     */
    isValid: boolean;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof VerifyResponse
     */
    signerIdentity?: { [key: string]: any; } | null;
    /**
     * 
     * @type {string}
     * @memberof VerifyResponse
     */
    signedAt?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VerifyResponse
     */
    claimGenerator?: string | null;
    /**
     * 
     * @type {string}
     * @memberof VerifyResponse
     */
    error?: string | null;
}

/**
 * Check if a given object implements the VerifyResponse interface.
 */
export function instanceOfVerifyResponse(value: object): value is VerifyResponse {
    if (!('isValid' in value) || value['isValid'] === undefined) return false;
    return true;
}

export function VerifyResponseFromJSON(json: any): VerifyResponse {
    return VerifyResponseFromJSONTyped(json, false);
}

export function VerifyResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): VerifyResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'isValid': json['is_valid'],
        'signerIdentity': json['signer_identity'] == null ? undefined : json['signer_identity'],
        'signedAt': json['signed_at'] == null ? undefined : json['signed_at'],
        'claimGenerator': json['claim_generator'] == null ? undefined : json['claim_generator'],
        'error': json['error'] == null ? undefined : json['error'],
    };
}

export function VerifyResponseToJSON(value?: VerifyResponse | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'is_valid': value['isValid'],
        'signer_identity': value['signerIdentity'],
        'signed_at': value['signedAt'],
        'claim_generator': value['claimGenerator'],
        'error': value['error'],
    };
}

