/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AudioDetectRequest,
  AudioDetectResponse,
  AudioEmbedRequest,
  AudioEmbedResponse,
  AudioHealthResponse,
  AudioSignRequest,
  AudioSignResponse,
  HTTPValidationError,
} from '../models/index';
import {
    AudioDetectRequestFromJSON,
    AudioDetectRequestToJSON,
    AudioDetectResponseFromJSON,
    AudioDetectResponseToJSON,
    AudioEmbedRequestFromJSON,
    AudioEmbedRequestToJSON,
    AudioEmbedResponseFromJSON,
    AudioEmbedResponseToJSON,
    AudioHealthResponseFromJSON,
    AudioHealthResponseToJSON,
    AudioSignRequestFromJSON,
    AudioSignRequestToJSON,
    AudioSignResponseFromJSON,
    AudioSignResponseToJSON,
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
} from '../models/index';

export interface AudioDetectAudioDetectPostRequest {
    audioDetectRequest: AudioDetectRequest;
    authorization?: string | null;
}

export interface AudioEmbedAudioEmbedPostRequest {
    audioEmbedRequest: AudioEmbedRequest;
    authorization?: string | null;
}

export interface AudioSignAudioSignPostRequest {
    audioSignRequest: AudioSignRequest;
    authorization?: string | null;
}

/**
 * 
 */
export class AudioApi extends runtime.BaseAPI {

    /**
     * Detect watermark in audio (server-side).
     * Audio Detect
     */
    async audioDetectAudioDetectPostRaw(requestParameters: AudioDetectAudioDetectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AudioDetectResponse>> {
        if (requestParameters['audioDetectRequest'] == null) {
            throw new runtime.RequiredError(
                'audioDetectRequest',
                'Required parameter "audioDetectRequest" was null or undefined when calling audioDetectAudioDetectPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/audio/detect`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AudioDetectRequestToJSON(requestParameters['audioDetectRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AudioDetectResponseFromJSON(jsonValue));
    }

    /**
     * Detect watermark in audio (server-side).
     * Audio Detect
     */
    async audioDetectAudioDetectPost(requestParameters: AudioDetectAudioDetectPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AudioDetectResponse> {
        const response = await this.audioDetectAudioDetectPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Embed spread-spectrum watermark into audio (server-side).
     * Audio Embed
     */
    async audioEmbedAudioEmbedPostRaw(requestParameters: AudioEmbedAudioEmbedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AudioEmbedResponse>> {
        if (requestParameters['audioEmbedRequest'] == null) {
            throw new runtime.RequiredError(
                'audioEmbedRequest',
                'Required parameter "audioEmbedRequest" was null or undefined when calling audioEmbedAudioEmbedPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/audio/embed`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AudioEmbedRequestToJSON(requestParameters['audioEmbedRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AudioEmbedResponseFromJSON(jsonValue));
    }

    /**
     * Embed spread-spectrum watermark into audio (server-side).
     * Audio Embed
     */
    async audioEmbedAudioEmbedPost(requestParameters: AudioEmbedAudioEmbedPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AudioEmbedResponse> {
        const response = await this.audioEmbedAudioEmbedPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Audio subsystem health check — no auth required.
     * Audio Health
     */
    async audioHealthAudioHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AudioHealthResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/audio/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AudioHealthResponseFromJSON(jsonValue));
    }

    /**
     * Audio subsystem health check — no auth required.
     * Audio Health
     */
    async audioHealthAudioHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AudioHealthResponse> {
        const response = await this.audioHealthAudioHealthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Full C2PA container signing with VouchCovenant + optional watermark.
     * Audio Sign
     */
    async audioSignAudioSignPostRaw(requestParameters: AudioSignAudioSignPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AudioSignResponse>> {
        if (requestParameters['audioSignRequest'] == null) {
            throw new runtime.RequiredError(
                'audioSignRequest',
                'Required parameter "audioSignRequest" was null or undefined when calling audioSignAudioSignPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/audio/sign`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AudioSignRequestToJSON(requestParameters['audioSignRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AudioSignResponseFromJSON(jsonValue));
    }

    /**
     * Full C2PA container signing with VouchCovenant + optional watermark.
     * Audio Sign
     */
    async audioSignAudioSignPost(requestParameters: AudioSignAudioSignPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AudioSignResponse> {
        const response = await this.audioSignAudioSignPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
