/* tslint:disable */
/* eslint-disable */
/**
 * Vouch Bridge
 * C2PA image signing, QR badge overlay, and audio watermarking service
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HTTPValidationError,
  HealthResponse,
  SignRequest,
  SignResponse,
  VerifyRequest,
  VerifyResponse,
} from '../models/index';
import {
    HTTPValidationErrorFromJSON,
    HTTPValidationErrorToJSON,
    HealthResponseFromJSON,
    HealthResponseToJSON,
    SignRequestFromJSON,
    SignRequestToJSON,
    SignResponseFromJSON,
    SignResponseToJSON,
    VerifyRequestFromJSON,
    VerifyRequestToJSON,
    VerifyResponseFromJSON,
    VerifyResponseToJSON,
} from '../models/index';

export interface SignImageSignPostRequest {
    signRequest: SignRequest;
    authorization?: string | null;
}

export interface VerifyImageVerifyPostRequest {
    verifyRequest: VerifyRequest;
    authorization?: string | null;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * Health check — no auth required.
     * Health
     */
    async healthHealthGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthResponse>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/health`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthResponseFromJSON(jsonValue));
    }

    /**
     * Health check — no auth required.
     * Health
     */
    async healthHealthGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthResponse> {
        const response = await this.healthHealthGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * Sign an image with C2PA manifest and QR badge.
     * Sign Image
     */
    async signImageSignPostRaw(requestParameters: SignImageSignPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SignResponse>> {
        if (requestParameters['signRequest'] == null) {
            throw new runtime.RequiredError(
                'signRequest',
                'Required parameter "signRequest" was null or undefined when calling signImageSignPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/sign`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SignRequestToJSON(requestParameters['signRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SignResponseFromJSON(jsonValue));
    }

    /**
     * Sign an image with C2PA manifest and QR badge.
     * Sign Image
     */
    async signImageSignPost(requestParameters: SignImageSignPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SignResponse> {
        const response = await this.signImageSignPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Verify a signed image\'s C2PA manifest.
     * Verify Image
     */
    async verifyImageVerifyPostRaw(requestParameters: VerifyImageVerifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<VerifyResponse>> {
        if (requestParameters['verifyRequest'] == null) {
            throw new runtime.RequiredError(
                'verifyRequest',
                'Required parameter "verifyRequest" was null or undefined when calling verifyImageVerifyPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (requestParameters['authorization'] != null) {
            headerParameters['authorization'] = String(requestParameters['authorization']);
        }

        const response = await this.request({
            path: `/verify`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: VerifyRequestToJSON(requestParameters['verifyRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => VerifyResponseFromJSON(jsonValue));
    }

    /**
     * Verify a signed image\'s C2PA manifest.
     * Verify Image
     */
    async verifyImageVerifyPost(requestParameters: VerifyImageVerifyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<VerifyResponse> {
        const response = await this.verifyImageVerifyPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
