name: Feature Request
description: Suggest a new feature for Vouch Protocol
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please fill out the form below.
  
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: I'm always frustrated when...
    validations:
      required: true
  
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like.
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other solutions or features you've considered.
  
  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this affect?
      options:
        - Signer
        - Verifier
        - Delegation Chains
        - Key Management
        - Integrations
        - Documentation
        - Other
  
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Any other context or screenshots.
