import sys
import os
import json
from server import create_identity, sign_image, verify_image

# Mocking Context for direct calls (FastMCP allows direct function calls usually, 
# but if decorated, we might need to access the underlying function or just import logic.
# FastMCP tools are usually just wrappers. Let's try calling them.

def run_test():
    print("🧪 Starting MCP Logic Test...")

    # 1. Create Identity
    print("\n1️⃣ Testing create_identity...")
    id_json = create_identity("Test User")
    print(f"   Result: {id_json[:50]}...")
    
    data = json.loads(id_json)
    if "private_key_jwk" not in data:
        print("❌ Failed to get private key")
        return
    
    priv_key = json.dumps(data["private_key_jwk"]) # sign_image expects stringified JWK
    print("✅ Identity created.")

    # 2. Create Dummy Image (C2PA needs a real image format usually, like JPG/PNG)
    # Creating a simple blank JPG using Code (or we can assume one exists)
    # Let's try to verify the logic fails gracefully on text file or check if we can make a tiny jpg.
    # Actually, c2pa-python might fail on .txt. Let's just create a dummy file and see if it handles bytes.
    # C2PA supports specific formats.
    # I'll create a minimal binary file and name it .jpg
    
    # Valid image is generated by generate_jpeg.py before this script runs.
    if not os.path.exists("test.jpg"):
        print("❌ test.jpg not found. Run generate_jpeg.py first.")
        return
    
    abs_path = os.path.abspath("test.jpg")
    print(f"\n2️⃣ Testing sign_image on {abs_path}...")
    
    # We expect this might fail if c2pa-python is strict about image validity, 
    # but the *logic flow* of the tool is what we are testing.
    result = sign_image(abs_path, priv_key, "Test Title")
    print(f"   Result: {result}")
    
    if "Error" in result and "format" not in result: # Allow format errors, but not code errors
        pass # It's okay if it fails on invalid jpeg, provided it didn't crash
        
    # Check if output file exists
    signed_path = abs_path.replace("test.jpg", "signed_test.jpg")
    
    # 3. Verify
    if os.path.exists(signed_path):
        print(f"\n3️⃣ Testing verify_image on {signed_path}...")
        v_result = verify_image(signed_path)
        print(f"   Result: {v_result}")
    else:
        print("\n⚠️ Signing didn't produce a file (expected if C2PA rejected fake JPEG), skipping verify.")
        # Try verifying the unsigned one just to ensure tool runs
        v_result = verify_image(abs_path)
        print(f"   Verify Unsigned Result: {v_result}")

    print("\n✅ MCP Logic Test Completed (If no python crashes occurred)")

if __name__ == "__main__":
    run_test()
