"""
One accountable agent task, end to end, over the Vouch MCP tool surface.

The Vouch MCP server exposes fifteen tools. Five issue and check credentials
(``sign``, ``verify``, ``create_session``, ``check_revocation``,
``get_identity``); the rest cover the trust *lifecycle* around an action --
who was authorized, whether their capabilities allowed it, whether their
session was still trusted, and who is accountable for the output afterward.

This walks a single realistic task through those lifecycle tools, in order,
naming the MCP tool at each step:

    delegate            supervisor grants the worker one narrowed capability
    check_action        the gate confirms the worker may run the tool (Shield)
    check_trust         the worker's session is still trusted enough to act
    disclose_ai_origin  the worker signs an AI-origin claim over its output
    scan                the output is checked for leaked keys before release
    reputation          the outcome updates the worker's standing
    attribute           authorship of the produced file is recorded

Every step here calls the same ``vouch`` library primitive the matching MCP
tool wraps, so the flow is fully runnable with just ``pip install
vouch-protocol`` -- no MCP client required. Over MCP, each step is one tool
call with the same arguments and the same verdict.

Run:
    python examples/mcp_trust_lifecycle.py
"""

from __future__ import annotations

import asyncio
import hashlib
import json
import tempfile

from vouch import Signer, delegate, generate_identity
from vouch.attribution import AttributionSession, blame, summarize
from vouch.autosign import sign_intent
from vouch.heartbeat import build_session_voucher
from vouch.reputation import MemoryReputationStore, ReputationEngine
from vouch.scan import scan_text
from vouch.shield.permissions import Capabilities, PermissionManager
from vouch.trust_entropy import evaluate_trust


def ident(domain: str) -> tuple[object, Signer]:
    kp = generate_identity(domain=domain)
    return kp, Signer(private_key=kp.private_key_jwk, did=kp.did)


def step(n: int, tool: str, line: str) -> None:
    print(f"\n[{n}] {tool}\n    {line}")


def main() -> None:
    supervisor_kp, supervisor = ident("supervisor.example.com")
    worker_kp, worker = ident("worker.example.com")

    print("Supervisor:", supervisor.get_did())
    print("Worker:    ", worker.get_did())

    # 1) delegate -- the supervisor authorizes the worker to do exactly one
    #    thing: write the monthly report. The grant can only be narrowed by
    #    anything the worker signs under it, never widened (Spec 9.3).
    grant = delegate(
        action="write",
        target="reports.example.com",
        resource="report:2026-07",
        to=worker.get_did(),
        signer=supervisor,
        valid_seconds=3600,
    )
    step(1, "delegate", f"granted write on report:2026-07 -> {grant['type']}")

    # 2) check_action -- before the worker runs its write_report tool, the
    #    capability gate confirms the worker's grant (filesystem: write) meets
    #    what the tool requires. A read-only worker would be denied here.
    manager = PermissionManager()
    manager.register_tool("write_report", {"filesystem": "write"})
    manager.set_capabilities(worker.get_did(), Capabilities.from_dict({"filesystem": "write"}))
    allowed, reason = manager.check_permission(worker.get_did(), "write_report")
    step(2, "check_action", "ALLOW" if allowed else f"DENY: {reason}")
    if not allowed:
        raise SystemExit("worker not permitted to write -- stopping")

    # 3) check_trust -- the worker holds a trust-decaying session voucher. A
    #    high-stakes write requires the *current* (post-decay) trust to still
    #    clear the bar. Fresh here, so it passes; hours later it might not.
    voucher = build_session_voucher(
        subject_did=worker.get_did(),
        validator_dids=[supervisor.get_did()],
        decay_lambda=0.0005,
        initial_trust=1.0,
        max_ttl_seconds=3600,
        scope=["write_report"],
        valid_seconds=3600,
    )
    trust = evaluate_trust(voucher, threshold=0.6)
    step(
        3,
        "check_trust",
        f"trust={trust.trust:.4f} vs 0.60 -> {'ALLOW' if trust.passed else 'DENY'}",
    )

    # The worker produces its output.
    report_body = "Q3 revenue up 12%. Report generated by an autonomous agent.\n"
    report_hash = "sha256:" + hashlib.sha256(report_body.encode()).hexdigest()

    # 4) disclose_ai_origin -- the worker signs a credential attesting that it
    #    produced this exact content, so any reader can verify the AI-origin
    #    claim rather than trust an unsigned label.
    disclosure = sign_intent(
        "disclose",
        target="reports.example.com/report:2026-07",
        resource=report_hash,
        signer=worker,
        publish=False,
    )
    step(4, "disclose_ai_origin", f"signed AI-origin over {report_hash[:23]}...")

    # 5) scan -- before the report leaves the trust boundary, its text is
    #    scanned for leaked key material. A clean report releases; had a stray
    #    seed been pasted in, this would flag it.
    findings = scan_text(report_body)
    step(5, "scan", "CLEAN" if not findings else f"LEAK RISK: {len(findings)} finding(s)")
    if findings:
        raise SystemExit("refusing to release output with leaked key material")

    # 6) reputation -- the task succeeded, so the worker's standing improves.
    #    Reputation is replayed from signed outcomes, not a trusted stored int.
    async def score_worker() -> object:
        engine = ReputationEngine(store=MemoryReputationStore())
        await engine.record_success(worker.get_did(), "report delivered")
        await engine.record_success(worker.get_did(), "passed key scan")
        return await engine.get_score(worker.get_did())

    score = asyncio.run(score_worker())
    step(6, "reputation", f"score={score.score}, success_rate={score.success_rate:.0%}")

    # 7) attribute -- authorship of the produced file is recorded in a signed
    #    manifest: how much the agent wrote vs. a human, blamable per line.
    workdir = tempfile.mkdtemp()
    session = AttributionSession(
        workdir,
        ai_did=worker.get_did(),
        ai_private_key_jwk=worker_kp.private_key_jwk,
        ai_public_key_jwk=worker_kp.public_key_jwk,
        model="worker-agent",
    )
    session.record_edit("report.md", after_content=report_body, before_content="")
    manifest = session.finalize(files={"report.md": report_body}, human_signer=supervisor)
    split = summarize(manifest)
    first = blame(manifest, "report.md")[0]
    step(
        7,
        "attribute",
        f"{split['aiPercent']:.0f}% AI / {split['humanPercent']:.0f}% human; "
        f"line 1 -> {first['source']}",
    )

    print("\nEvery step is one MCP tool call. The whole task is now accountable:")
    print("  authorized (delegate), gated (check_action), trusted (check_trust),")
    print("  disclosed (disclose_ai_origin), clean (scan), scored (reputation),")
    print("  and attributed (attribute) -- each backed by a verifiable signature.")
    # Silence unused-variable linters: these credentials would travel with the
    # request over MCP; here we just confirm they were produced.
    assert grant and disclosure and json.dumps(manifest)


if __name__ == "__main__":
    main()
