#!/usr/bin/env python3
"""Set up an identity, rules, and files for the Vouch-protected MCP server.

    python3 examples/mcp_server/setup_demo.py --out /tmp/vouch-demo

Mints a ``did:key`` identity (self-certifying, so it resolves offline with no
DID document to host), writes a Shield rules file naming that DID, and creates a
small tree to act on. Prints the environment both servers need.
"""

from __future__ import annotations

import argparse
import base64
import json
import sys
from pathlib import Path

from vouch import multikey
from vouch.keys import generate_identity

RULES = """\
# Shield v2 rules for the Vouch-protected MCP server. Generated by setup_demo.py.
#
# Glob semantics on `resource`, where a segment is the text between '/':
#   *   exactly one segment; never crosses '/'
#   **  zero or more segments

version: 2
rules:
  - did: {did}
    allow:
      - id: read-reports
        action: read_file
        target: files
        resource: "reports/**"

      - id: list-reports
        action: list_dir
        target: files
        resource: "reports/**"

      # Deliberately absent: write_file and delete_file, and anything outside
      # reports/. secrets/ is not covered, so it is refused.
deny_default: true
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--out", default="/tmp/vouch-demo", help="demo directory")
    args = parser.parse_args()

    out = Path(args.out)
    (out / "reports").mkdir(parents=True, exist_ok=True)
    (out / "secrets").mkdir(parents=True, exist_ok=True)

    keypair = generate_identity()
    raw = base64.urlsafe_b64decode(json.loads(keypair.public_key_jwk)["x"] + "==")
    did = "did:key:" + multikey.encode_ed25519_public(raw)

    (out / "agent.jwk").write_text(keypair.private_key_jwk)
    (out / "rules.yaml").write_text(RULES.format(did=did))
    (out / "reports" / "q3.txt").write_text("Q3 revenue: up and to the right.\n")
    (out / "secrets" / "keys.txt").write_text("this file must never be read\n")

    print(f"Demo directory: {out}")
    print(f"  agent DID  : {did}")
    print("  rules      : read_file + list_dir on reports/** and nothing else")
    print("  files      : reports/q3.txt, secrets/keys.txt")
    print()
    print("Environment for the protected server:")
    print()
    print(f'  export VOUCH_FS_ROOT="{out}"')
    print(f'  export VOUCH_RULES="{out}/rules.yaml"')
    print(f'  export VOUCH_TRUSTED_ISSUERS="{did}"')
    print('  export VOUCH_TARGET="files"')
    print()
    print("And for vouch-mcp, the signer:")
    print()
    print(f'  export VOUCH_DID="{did}"')
    print(f'  export VOUCH_PRIVATE_KEY="$(cat {out}/agent.jwk)"')
    return 0


if __name__ == "__main__":
    sys.exit(main())
