// Cross-implementation interop test for the Vouch Protocol Root of Trust for
// Machine Identity (Specification §18). Loads the shared vector generated by
// the Python implementation and asserts that:
//
//  1. The Go verifier accepts the Python-signed identity chain and anchors it
//     to the pinned root, surfacing the expected agent, issuer, and root DIDs.
//  2. Building the three credentials from the same fixed inputs reproduces the
//     committed proofValues byte-for-byte, confirming Python and Go sign
//     identically for this payload.
//  3. Tampering with the identity proofValue is rejected.
//
// The Python suite has parallel tests against the same vector.

package signer

import (
	"bytes"
	"crypto/ed25519"
	"encoding/json"
	"os"
	"path/filepath"
	"testing"
	"time"
)

// rootOfTrustVector is the committed interop vector.
type rootOfTrustVector struct {
	TrustedRoot      string         `json:"trustedRoot"`
	RootOfTrust      map[string]any `json:"rootOfTrust"`
	RecognizedIssuer map[string]any `json:"recognizedIssuer"`
	AgentIdentity    map[string]any `json:"agentIdentity"`
	Expected         struct {
		VerifyIdentityChain bool   `json:"verifyIdentityChain"`
		AgentDid            string `json:"agentDid"`
		IssuerDid           string `json:"issuerDid"`
	} `json:"expected"`
}

func loadRootOfTrustVector(t *testing.T) rootOfTrustVector {
	t.Helper()
	wd, err := os.Getwd()
	if err != nil {
		t.Fatal(err)
	}
	repoRoot := filepath.Clean(filepath.Join(wd, "..", ".."))
	vecPath := filepath.Join(repoRoot, "test-vectors", "root-of-trust", "vector.json")
	raw, err := os.ReadFile(vecPath)
	if err != nil {
		t.Fatalf("read vector: %v", err)
	}
	var v rootOfTrustVector
	if err := json.Unmarshal(raw, &v); err != nil {
		t.Fatalf("decode vector: %v", err)
	}
	return v
}

// fixedSigner builds a did:key Signer from a repeated-byte seed, matching the
// fixed inputs used to generate the interop vector.
func fixedSigner(t *testing.T, seedByte byte) *Signer {
	t.Helper()
	seed := bytes.Repeat([]byte{seedByte}, ed25519.SeedSize)
	priv := ed25519.NewKeyFromSeed(seed)
	pub := priv.Public().(ed25519.PublicKey)
	did, err := DIDKeyFromEd25519(pub)
	if err != nil {
		t.Fatalf("DIDKeyFromEd25519: %v", err)
	}
	s, err := New(Config{DID: did, Ed25519Seed: seed, DefaultExpirySeconds: 300})
	if err != nil {
		t.Fatalf("New: %v", err)
	}
	return s
}

// TestRootOfTrustVerifyPythonChain checks the Go verifier accepts the
// Python-signed chain and anchors it to the pinned root (deliverable (a)).
func TestRootOfTrustVerifyPythonChain(t *testing.T) {
	vec := loadRootOfTrustVector(t)

	res := VerifyIdentityChain(VerifyIdentityChainOptions{
		IdentityCredential:         vec.AgentIdentity,
		RecognizedIssuerCredential: vec.RecognizedIssuer,
		RootCredential:             vec.RootOfTrust,
		TrustedRoot:                vec.TrustedRoot,
	})
	if !res.Ok {
		t.Fatalf("Go verifier rejected the Python-signed chain: %s", res.Reason)
	}
	if res.AgentDID != vec.Expected.AgentDid {
		t.Fatalf("agent DID mismatch\n expected: %s\n got:      %s", vec.Expected.AgentDid, res.AgentDID)
	}
	if res.IssuerDID != vec.Expected.IssuerDid {
		t.Fatalf("issuer DID mismatch\n expected: %s\n got:      %s", vec.Expected.IssuerDid, res.IssuerDID)
	}
	if res.RootDID != vec.TrustedRoot {
		t.Fatalf("root DID mismatch\n expected: %s\n got:      %s", vec.TrustedRoot, res.RootDID)
	}
}

// TestRootOfTrustReproduceVector rebuilds the three credentials from the same
// fixed inputs and asserts each proofValue matches the committed vector
// byte-for-byte (deliverable (b)).
func TestRootOfTrustReproduceVector(t *testing.T) {
	vec := loadRootOfTrustVector(t)

	rootSigner := fixedSigner(t, 0x01)
	issuerSigner := fixedSigner(t, 0x02)
	agentSigner := fixedSigner(t, 0x03)

	fixedTime := time.Date(2026, 1, 1, 0, 0, 0, 0, time.UTC)
	validSeconds := 100 * 365 * 24 * 3600

	root, err := BuildRootOfTrust(rootSigner, RootOfTrustOptions{
		Name:         "Vouch Machine Identity Root",
		Scope:        []string{"ai-agent", "robot"},
		ValidSeconds: validSeconds,
		ValidFrom:    fixedTime,
		Created:      fixedTime,
		CredentialID: "urn:uuid:11111111-1111-1111-1111-111111111111",
	})
	if err != nil {
		t.Fatalf("BuildRootOfTrust: %v", err)
	}

	recognized, err := BuildRecognizedIssuer(rootSigner, RecognizedIssuerOptions{
		IssuerDID:         issuerSigner.DID(),
		RecognizedActions: []string{ActionIssueAgentIdentity},
		ValidSeconds:      validSeconds,
		ValidFrom:         fixedTime,
		Created:           fixedTime,
		CredentialID:      "urn:uuid:22222222-2222-2222-2222-222222222222",
	})
	if err != nil {
		t.Fatalf("BuildRecognizedIssuer: %v", err)
	}

	identity, err := BuildAgentIdentity(issuerSigner, AgentIdentityOptions{
		SubjectDID: agentSigner.DID(),
		Attributes: map[string]any{
			"owner":           "Acme",
			"model":           "gpt-x",
			"capabilityClass": "shopping",
		},
		ValidSeconds: validSeconds,
		ValidFrom:    fixedTime,
		Created:      fixedTime,
		CredentialID: "urn:uuid:33333333-3333-3333-3333-333333333333",
	})
	if err != nil {
		t.Fatalf("BuildAgentIdentity: %v", err)
	}

	cases := []struct {
		name  string
		built map[string]any
		want  map[string]any
	}{
		{"rootOfTrust", root, vec.RootOfTrust},
		{"recognizedIssuer", recognized, vec.RecognizedIssuer},
		{"agentIdentity", identity, vec.AgentIdentity},
	}
	for _, tc := range cases {
		gotPV := proofValue(t, tc.built)
		wantPV := proofValue(t, tc.want)
		if gotPV != wantPV {
			t.Errorf(
				"%s proofValue not byte-identical to Python vector\n expected: %s\n got:      %s",
				tc.name, wantPV, gotPV,
			)
		}
	}

	// The rebuilt chain must also verify and anchor to the same root, proving
	// the freshly built credentials interoperate with the verifier.
	res := VerifyIdentityChain(VerifyIdentityChainOptions{
		IdentityCredential:         identity,
		RecognizedIssuerCredential: recognized,
		RootCredential:             root,
		TrustedRoot:                rootSigner.DID(),
	})
	if !res.Ok {
		t.Fatalf("rebuilt chain failed verification: %s", res.Reason)
	}
	if res.RootDID != vec.TrustedRoot {
		t.Fatalf("rebuilt root DID %s does not match vector trustedRoot %s", res.RootDID, vec.TrustedRoot)
	}
}

// TestRootOfTrustRejectsTamperedIdentity tampers with the identity proofValue
// and asserts the chain is rejected (deliverable (c)).
func TestRootOfTrustRejectsTamperedIdentity(t *testing.T) {
	vec := loadRootOfTrustVector(t)

	tampered := copyMap(vec.AgentIdentity)
	proof := copyMap(tampered["proof"].(map[string]any))
	pv := proof["proofValue"].(string)
	// Flip the last character to a different valid base58 symbol.
	last := pv[len(pv)-1]
	replacement := byte('2')
	if last == replacement {
		replacement = '3'
	}
	proof["proofValue"] = pv[:len(pv)-1] + string(replacement)
	tampered["proof"] = proof

	res := VerifyIdentityChain(VerifyIdentityChainOptions{
		IdentityCredential:         tampered,
		RecognizedIssuerCredential: vec.RecognizedIssuer,
		RootCredential:             vec.RootOfTrust,
		TrustedRoot:                vec.TrustedRoot,
	})
	if res.Ok {
		t.Fatal("expected verification to reject a tampered identity proofValue")
	}
	if res.Reason != "identity_proof_invalid" {
		t.Fatalf("unexpected rejection reason: %s", res.Reason)
	}
}

// proofValue extracts credential["proof"]["proofValue"] as a string.
func proofValue(t *testing.T, credential map[string]any) string {
	t.Helper()
	proof, ok := credential["proof"].(map[string]any)
	if !ok {
		t.Fatal("credential has no proof object")
	}
	pv, ok := proof["proofValue"].(string)
	if !ok {
		t.Fatal("proof has no proofValue")
	}
	return pv
}
