# coding: utf-8

# flake8: noqa
"""
    Vouch Bridge

    C2PA image signing, QR badge overlay, and audio watermarking service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from vouch_api_client.models.audio_detect_request import AudioDetectRequest
from vouch_api_client.models.audio_detect_response import AudioDetectResponse
from vouch_api_client.models.audio_embed_request import AudioEmbedRequest
from vouch_api_client.models.audio_embed_response import AudioEmbedResponse
from vouch_api_client.models.audio_health_response import AudioHealthResponse
from vouch_api_client.models.audio_sign_request import AudioSignRequest
from vouch_api_client.models.audio_sign_response import AudioSignResponse
from vouch_api_client.models.http_validation_error import HTTPValidationError
from vouch_api_client.models.health_response import HealthResponse
from vouch_api_client.models.sign_request import SignRequest
from vouch_api_client.models.sign_response import SignResponse
from vouch_api_client.models.validation_error import ValidationError
from vouch_api_client.models.validation_error_loc_inner import ValidationErrorLocInner
from vouch_api_client.models.verify_request import VerifyRequest
from vouch_api_client.models.verify_response import VerifyResponse
