# coding: utf-8

"""
    Vouch Bridge

    C2PA image signing, QR badge overlay, and audio watermarking service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AudioEmbedRequest(BaseModel):
    """
    Request body for POST /audio/embed.
    """ # noqa: E501
    audio_base64: StrictStr = Field(description="Base64-encoded audio (WAV/MP3/FLAC/OGG/M4A/AAC/Opus/WebM)")
    did: StrictStr = Field(description="DID of the signer")
    display_name: Optional[StrictStr] = Field(default='', description="Human-readable signer name")
    covenant: Optional[Dict[str, Any]] = None
    __properties: ClassVar[List[str]] = ["audio_base64", "did", "display_name", "covenant"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AudioEmbedRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if covenant (nullable) is None
        # and model_fields_set contains the field
        if self.covenant is None and "covenant" in self.model_fields_set:
            _dict['covenant'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AudioEmbedRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "audio_base64": obj.get("audio_base64"),
            "did": obj.get("did"),
            "display_name": obj.get("display_name") if obj.get("display_name") is not None else '',
            "covenant": obj.get("covenant")
        })
        return _obj


