# coding: utf-8

"""
    Vouch Bridge

    C2PA image signing, QR badge overlay, and audio watermarking service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class AudioEmbedResponse(BaseModel):
    """
    Response body for POST /audio/embed.
    """ # noqa: E501
    success: StrictBool
    audio_base64: Optional[StrictStr] = None
    watermark_id: Optional[StrictStr] = None
    audio_hash: Optional[StrictStr] = None
    payload_hash: Optional[StrictStr] = None
    timestamp: Optional[StrictStr] = None
    error: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["success", "audio_base64", "watermark_id", "audio_hash", "payload_hash", "timestamp", "error"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AudioEmbedResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if audio_base64 (nullable) is None
        # and model_fields_set contains the field
        if self.audio_base64 is None and "audio_base64" in self.model_fields_set:
            _dict['audio_base64'] = None

        # set to None if watermark_id (nullable) is None
        # and model_fields_set contains the field
        if self.watermark_id is None and "watermark_id" in self.model_fields_set:
            _dict['watermark_id'] = None

        # set to None if audio_hash (nullable) is None
        # and model_fields_set contains the field
        if self.audio_hash is None and "audio_hash" in self.model_fields_set:
            _dict['audio_hash'] = None

        # set to None if payload_hash (nullable) is None
        # and model_fields_set contains the field
        if self.payload_hash is None and "payload_hash" in self.model_fields_set:
            _dict['payload_hash'] = None

        # set to None if timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp is None and "timestamp" in self.model_fields_set:
            _dict['timestamp'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AudioEmbedResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "audio_base64": obj.get("audio_base64"),
            "watermark_id": obj.get("watermark_id"),
            "audio_hash": obj.get("audio_hash"),
            "payload_hash": obj.get("payload_hash"),
            "timestamp": obj.get("timestamp"),
            "error": obj.get("error")
        })
        return _obj


