# coding: utf-8

"""
    Vouch Bridge

    C2PA image signing, QR badge overlay, and audio watermarking service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictFloat, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional, Union
from typing import Optional, Set
from typing_extensions import Self

class AudioDetectResponse(BaseModel):
    """
    Response body for POST /audio/detect.
    """ # noqa: E501
    success: StrictBool
    detected: Optional[StrictBool] = False
    confidence: Optional[Union[StrictFloat, StrictInt]] = 0.0
    signer_did: Optional[StrictStr] = None
    payload_hash: Optional[StrictStr] = None
    covenant: Optional[Dict[str, Any]] = None
    error: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["success", "detected", "confidence", "signer_did", "payload_hash", "covenant", "error"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AudioDetectResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if signer_did (nullable) is None
        # and model_fields_set contains the field
        if self.signer_did is None and "signer_did" in self.model_fields_set:
            _dict['signer_did'] = None

        # set to None if payload_hash (nullable) is None
        # and model_fields_set contains the field
        if self.payload_hash is None and "payload_hash" in self.model_fields_set:
            _dict['payload_hash'] = None

        # set to None if covenant (nullable) is None
        # and model_fields_set contains the field
        if self.covenant is None and "covenant" in self.model_fields_set:
            _dict['covenant'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AudioDetectResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "detected": obj.get("detected") if obj.get("detected") is not None else False,
            "confidence": obj.get("confidence") if obj.get("confidence") is not None else 0.0,
            "signer_did": obj.get("signer_did"),
            "payload_hash": obj.get("payload_hash"),
            "covenant": obj.get("covenant"),
            "error": obj.get("error")
        })
        return _obj


