# coding: utf-8

"""
    Vouch Bridge

    C2PA image signing, QR badge overlay, and audio watermarking service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SignResponse(BaseModel):
    """
    Response body for POST /sign.
    """ # noqa: E501
    success: StrictBool
    signed_image_base64: Optional[StrictStr] = None
    manifest_hash: Optional[StrictStr] = None
    verify_url: Optional[StrictStr] = None
    timestamp: Optional[StrictStr] = None
    error: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["success", "signed_image_base64", "manifest_hash", "verify_url", "timestamp", "error"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SignResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if signed_image_base64 (nullable) is None
        # and model_fields_set contains the field
        if self.signed_image_base64 is None and "signed_image_base64" in self.model_fields_set:
            _dict['signed_image_base64'] = None

        # set to None if manifest_hash (nullable) is None
        # and model_fields_set contains the field
        if self.manifest_hash is None and "manifest_hash" in self.model_fields_set:
            _dict['manifest_hash'] = None

        # set to None if verify_url (nullable) is None
        # and model_fields_set contains the field
        if self.verify_url is None and "verify_url" in self.model_fields_set:
            _dict['verify_url'] = None

        # set to None if timestamp (nullable) is None
        # and model_fields_set contains the field
        if self.timestamp is None and "timestamp" in self.model_fields_set:
            _dict['timestamp'] = None

        # set to None if error (nullable) is None
        # and model_fields_set contains the field
        if self.error is None and "error" in self.model_fields_set:
            _dict['error'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SignResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "success": obj.get("success"),
            "signed_image_base64": obj.get("signed_image_base64"),
            "manifest_hash": obj.get("manifest_hash"),
            "verify_url": obj.get("verify_url"),
            "timestamp": obj.get("timestamp"),
            "error": obj.get("error")
        })
        return _obj


