# coding: utf-8

"""
    Vouch Bridge

    C2PA image signing, QR badge overlay, and audio watermarking service

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self

class SignRequest(BaseModel):
    """
    Request body for POST /sign.
    """ # noqa: E501
    image_base64: StrictStr = Field(description="Base64-encoded source image")
    did: StrictStr = Field(description="DID of the signer")
    display_name: StrictStr = Field(description="Human-readable signer name")
    email: Optional[StrictStr] = None
    credential_type: Optional[StrictStr] = Field(default='FREE', description="FREE or PRO")
    title: Optional[StrictStr] = None
    badge_position: Optional[StrictStr] = None
    shortlink_domain: Optional[StrictStr] = None
    __properties: ClassVar[List[str]] = ["image_base64", "did", "display_name", "email", "credential_type", "title", "badge_position", "shortlink_domain"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SignRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if email (nullable) is None
        # and model_fields_set contains the field
        if self.email is None and "email" in self.model_fields_set:
            _dict['email'] = None

        # set to None if title (nullable) is None
        # and model_fields_set contains the field
        if self.title is None and "title" in self.model_fields_set:
            _dict['title'] = None

        # set to None if badge_position (nullable) is None
        # and model_fields_set contains the field
        if self.badge_position is None and "badge_position" in self.model_fields_set:
            _dict['badge_position'] = None

        # set to None if shortlink_domain (nullable) is None
        # and model_fields_set contains the field
        if self.shortlink_domain is None and "shortlink_domain" in self.model_fields_set:
            _dict['shortlink_domain'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SignRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "image_base64": obj.get("image_base64"),
            "did": obj.get("did"),
            "display_name": obj.get("display_name"),
            "email": obj.get("email"),
            "credential_type": obj.get("credential_type") if obj.get("credential_type") is not None else 'FREE',
            "title": obj.get("title"),
            "badge_position": obj.get("badge_position"),
            "shortlink_domain": obj.get("shortlink_domain")
        })
        return _obj


