#ifndef VOUCH_CORE_H
#define VOUCH_CORE_H

/* Generated by cbindgen from the Vouch Protocol core (core/uniffi/src/c_api.rs). Do not edit by hand. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

/**
 * Free a string returned by this library.
 */
void vouch_string_free(char *s);

/**
 * Library version (caller frees).
 */
char *vouch_version(void);

/**
 * RFC 8785 canonicalization of a JSON string. NULL on error.
 */
char *vouch_canonicalize(const char *json, char **err_out);

/**
 * Generate an Ed25519 key pair. Returns JSON {seed_b64, public_b64, multikey, did_key}.
 */
char *vouch_generate_ed25519(char **err_out);

/**
 * Sign a credential (eddsa-jcs-2022). seed_b64 is the 32-byte Ed25519 seed.
 */
char *vouch_sign_credential(const char *credential_json,
                            const char *seed_b64,
                            const char *verification_method,
                            const char *created,
                            char **err_out);

/**
 * Build a detached eddsa-jcs-2022 proof object (JSON).
 */
char *vouch_build_proof(const char *credential_json,
                        const char *seed_b64,
                        const char *verification_method,
                        const char *created,
                        char **err_out);

/**
 * Verify an eddsa-jcs-2022 proof. Returns "true"/"false".
 */
char *vouch_verify_proof(const char *credential_json, const char *public_b64, char **err_out);

/**
 * Verify a credential's proof and validity window. Returns JSON
 * {proofValid, timeValid, valid}.
 */
char *vouch_verify_credential(const char *credential_json,
                              const char *public_b64,
                              const char *now_iso,
                              int64_t clock_skew_seconds,
                              char **err_out);

/**
 * Verify a dual proof (Ed25519 + ML-DSA-44). Returns "true"/"false".
 */
char *vouch_verify_dual(const char *credential_json,
                        const char *ed25519_public_b64,
                        const char *mldsa_public_b64,
                        char **err_out);

/**
 * Verify a v1.6.x composite hybrid proof. Returns "true"/"false".
 */
char *vouch_verify_composite(const char *credential_json,
                             const char *ed25519_public_b64,
                             const char *mldsa_public_b64,
                             char **err_out);

/**
 * Verify a credential's revocation status against a BitstringStatusList
 * credential. Returns "true" (set/revoked) or "false".
 */
char *vouch_verify_status(const char *credential_status_json,
                          const char *status_list_credential_json,
                          char **err_out);

/**
 * Build a delegation link. The valid_from / valid_until / parent_proof_value
 * arguments are optional: pass NULL to omit them. Returns the link as JSON.
 */
char *vouch_build_delegation_link(const char *issuer,
                                  const char *subject,
                                  const char *intent_json,
                                  const char *valid_from,
                                  const char *valid_until,
                                  const char *parent_proof_value,
                                  char **err_out);

/**
 * Validate the time-bound rule over a delegation chain (a JSON array of links).
 * Returns "true"/"false".
 */
char *vouch_verify_chain_time_bound(const char *chain_json,
                                    const char *now_iso,
                                    int64_t clock_skew_seconds,
                                    char **err_out);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* VOUCH_CORE_H */
