"""Vouch Gatekeeper — leak-check extension.

PR-scoped scan that runs the OSS PAD-058 detector (`vouch.scan`)
against every file changed in the pull request. Fails the check
when Vouch-shaped private key material is found.

Wire-in: `handle_pull_request` in main.py runs `run_leak_check`
concurrently with the existing signature evaluation. A separate
check named "Vouch Leak Check" is posted alongside the existing
"Vouch Gatekeeper" check.
"""

from __future__ import annotations

import base64
import logging
from dataclasses import dataclass
from typing import TYPE_CHECKING, Any

from vouch.scan import scan_text, Severity, Kind, Finding

if TYPE_CHECKING:
    from main import GitHubClient

logger = logging.getLogger(__name__)


# Per-PR limits to keep webhook latency bounded.
MAX_FILES_PER_PR = 100
MAX_FILE_BYTES = 5 * 1024 * 1024


@dataclass
class LeakCheckResult:
    """Result of a PR leak scan, ready to post as a check run."""

    findings: list[Finding]
    files_scanned: int
    files_skipped: int

    @property
    def critical_count(self) -> int:
        return sum(1 for f in self.findings if f.severity == Severity.CRITICAL)

    @property
    def high_count(self) -> int:
        return sum(1 for f in self.findings if f.severity == Severity.HIGH)

    @property
    def medium_count(self) -> int:
        return sum(1 for f in self.findings if f.severity == Severity.MEDIUM)

    @property
    def conclusion(self) -> str:
        """GitHub check-run conclusion: failure, neutral, or success."""
        if self.critical_count or self.high_count:
            return "failure"
        if self.medium_count:
            return "neutral"
        return "success"

    @property
    def title(self) -> str:
        if self.critical_count:
            return f"Vouch Leak Check: {self.critical_count} critical finding(s)"
        if self.high_count:
            return f"Vouch Leak Check: {self.high_count} high-severity finding(s)"
        if self.medium_count:
            return f"Vouch Leak Check: {self.medium_count} medium finding(s) to verify"
        return "Vouch Leak Check: no Vouch-shaped key material detected"

    @property
    def summary(self) -> str:
        if not self.findings:
            return (
                f"Scanned {self.files_scanned} file(s) in this PR. No Vouch-shaped "
                f"private key material detected.\n\n"
                f"This check uses the PAD-058 detection patterns from "
                f"[vouch.scan](https://github.com/vouch-protocol/vouch/blob/main/vouch/scan/)."
            )
        return (
            f"Scanned {self.files_scanned} file(s). Found "
            f"**{self.critical_count} critical**, **{self.high_count} high**, "
            f"**{self.medium_count} medium** finding(s).\n\n"
            f"This check fails when Vouch-shaped private key material is committed to "
            f"the repository. Rotate the affected DIDs immediately and remove the "
            f"material from history."
        )

    def details_markdown(self) -> str:
        """Long-form markdown for the check-run `text` field."""
        if not self.findings:
            return ""
        lines: list[str] = []
        for sev in [Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW]:
            items = [f for f in self.findings if f.severity == sev]
            if not items:
                continue
            lines.append(f"## {sev.value.upper()} ({len(items)})")
            lines.append("")
            for f in items:
                lines.append(f"### `{f.file}` (line {f.line})")
                lines.append("")
                lines.append(f"**Kind:** `{f.kind.value}`")
                lines.append(f"**Description:** {f.description}")
                lines.append(f"**Match hash:** `{f.matched_hash}`")
                lines.append("")
                lines.append("**Remediation:**")
                lines.append("")
                lines.append(f"> {f.remediation}")
                lines.append("")
        lines.append("---")
        lines.append("")
        lines.append(
            "Generated by Vouch Gatekeeper leak check "
            "([PAD-058](https://github.com/vouch-protocol/vouch/blob/main/docs/disclosures/PAD-058-automated-key-rotation-on-leak-detection.md), "
            "[vouch.scan](https://github.com/vouch-protocol/vouch/blob/main/vouch/scan/))."
        )
        return "\n".join(lines)


async def _get_pr_files(
    github: "GitHubClient", owner: str, repo: str, pr_number: int
) -> list[dict[str, Any]]:
    """Return the list of files changed in a PR (paginated).

    Uses GitHub's `/repos/{owner}/{repo}/pulls/{pr_number}/files` endpoint.
    """
    all_files: list[dict[str, Any]] = []
    page = 1
    while True:
        endpoint = f"/repos/{owner}/{repo}/pulls/{pr_number}/files?per_page=100&page={page}"
        try:
            batch = await github._request("GET", endpoint)
        except Exception as exc:
            logger.warning("leak_check: failed to list PR files: %s", exc)
            break
        if not batch:
            break
        all_files.extend(batch)
        if len(batch) < 100:
            break
        page += 1
        if len(all_files) >= MAX_FILES_PER_PR:
            break
    return all_files[:MAX_FILES_PER_PR]


async def _get_blob_text(
    github: "GitHubClient", owner: str, repo: str, sha: str
) -> str | None:
    """Fetch a blob's content (text) by SHA via the git blob API."""
    endpoint = f"/repos/{owner}/{repo}/git/blobs/{sha}"
    try:
        blob = await github._request("GET", endpoint)
    except Exception as exc:
        logger.warning("leak_check: failed to fetch blob %s: %s", sha, exc)
        return None
    if not blob:
        return None
    if blob.get("encoding") != "base64":
        return None
    try:
        raw = base64.b64decode(blob.get("content", ""))
    except Exception:
        return None
    if len(raw) > MAX_FILE_BYTES:
        return None
    try:
        return raw.decode("utf-8", errors="replace")
    except Exception:
        return None


async def run_leak_check(
    github: "GitHubClient",
    owner: str,
    repo_name: str,
    pr_number: int,
) -> LeakCheckResult:
    """Run the PAD-058 detector against every file changed in the PR.

    Returns a structured result. The caller posts it as a check run.
    """
    files = await _get_pr_files(github, owner, repo_name, pr_number)
    findings: list[Finding] = []
    scanned = 0
    skipped = 0

    for f in files:
        filename = f.get("filename", "")
        status = f.get("status", "")
        # Removed files have nothing to scan; deletion of a leak is good news.
        if status == "removed":
            continue
        sha = f.get("sha")  # blob SHA at the head of the PR
        if not sha:
            skipped += 1
            continue
        content = await _get_blob_text(github, owner, repo_name, sha)
        if content is None:
            skipped += 1
            continue
        scanned += 1
        # scan_text excludes the filename-only pattern; we apply that
        # independently here against the filename.
        for finding in scan_text(content, file_label=filename):
            findings.append(finding)
        if _matches_vouch_config_filename(filename):
            findings.append(
                _make_filename_finding(filename)
            )

    return LeakCheckResult(findings=findings, files_scanned=scanned, files_skipped=skipped)


def _matches_vouch_config_filename(filename: str) -> bool:
    from vouch.scan.patterns import VOUCH_CONFIG_FILENAME_RE

    return bool(VOUCH_CONFIG_FILENAME_RE.match(filename))


def _make_filename_finding(filename: str) -> Finding:
    import hashlib

    return Finding(
        kind=Kind.VOUCH_CONFIG_FILENAME,
        severity=Severity.MEDIUM,
        file=filename,
        line=1,
        column=1,
        snippet=filename,
        matched_hash="sha256:" + hashlib.sha256(filename.encode()).hexdigest()[:16],
        description=(
            "Vouch-specific config filename — verify the file does not "
            "contain private key material"
        ),
        remediation=(
            "Add the file to .gitignore if it carries keys. Move keys to a "
            "secret manager. Keep only the DID and configuration metadata in "
            "tracked files."
        ),
    )
