/**
 * Cross-implementation interop test for the hybrid Ed25519 + ML-DSA-44
 * cryptosuite (W3C CG Report §13.2).
 *
 * Loads the shared vector at test-vectors/hybrid-eddsa-mldsa44/vector.json
 * which was generated by the Python implementation, and asserts that:
 *   1. JCS canonicalization of the signed credential (with proofValue
 *      stripped) produces the documented SHA-256 digest, confirming that
 *      Python and TypeScript canonicalize identically for this payload.
 *   2. The TypeScript verifier accepts the Python-generated hybrid
 *      signature, confirming wire-format interop.
 *
 * The Go test suite has a parallel test reading the same vector.
 */

import * as crypto from 'crypto';
import * as fs from 'fs';
import * as path from 'path';

import { canonicalize, verifyHybridProof } from '../src';

interface HybridVector {
    description: string;
    version: string;
    ed25519: { seed_b64: string; public_key_b64: string };
    mldsa44: { public_key_b64: string; secret_key_b64: string };
    expected_canonical_sha256_b64: string;
    signed_credential: Record<string, unknown> & {
        proof: { proofValue: string; [k: string]: unknown };
    };
}

const VECTOR_PATH = path.resolve(
    __dirname,
    '..',
    '..',
    '..',
    'test-vectors',
    'hybrid-eddsa-mldsa44',
    'vector.json'
);

function loadVector(): HybridVector {
    return JSON.parse(fs.readFileSync(VECTOR_PATH, 'utf-8')) as HybridVector;
}

function b64(s: string): Uint8Array {
    return new Uint8Array(Buffer.from(s, 'base64'));
}

describe('Hybrid cross-implementation interop', () => {
    test('JCS canonicalization produces the documented SHA-256 digest', () => {
        const vec = loadVector();

        // Reconstruct the canonical form by stripping proofValue and
        // canonicalizing what remains (this is what the verifier does).
        const cred: Record<string, unknown> = JSON.parse(
            JSON.stringify(vec.signed_credential)
        );
        const proof = cred.proof as Record<string, unknown>;
        delete proof.proofValue;

        const canonical = canonicalize(cred);
        const digest = crypto.createHash('sha256').update(canonical).digest();
        const digestB64 = digest.toString('base64');

        expect(digestB64).toBe(vec.expected_canonical_sha256_b64);
    });

    test('TypeScript verifier accepts a Python-generated hybrid signature', () => {
        const vec = loadVector();

        // Reconstruct the Ed25519 public key from the documented raw bytes.
        const edRaw = b64(vec.ed25519.public_key_b64);
        // Build a JWK then a Node KeyObject.
        const x = Buffer.from(edRaw)
            .toString('base64')
            .replace(/\+/g, '-')
            .replace(/\//g, '_')
            .replace(/=+$/, '');
        const ed25519PublicKey = crypto.createPublicKey({
            key: { kty: 'OKP', crv: 'Ed25519', x } as crypto.JsonWebKey,
            format: 'jwk',
        });

        const mldsa44PublicKey = b64(vec.mldsa44.public_key_b64);

        const ok = verifyHybridProof(
            vec.signed_credential,
            ed25519PublicKey,
            mldsa44PublicKey
        );
        expect(ok).toBe(true);
    });
});
